apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-blue
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
      version: blue
  template:
    metadata:
      labels:
        app: node
        version: blue
    spec:
      containers:
      - name: node
        image: kalianonymous/node-devops:v1
        ports:
        - containerPort: 3000
