apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-green
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
      version: green
  template:
    metadata:
      labels:
        app: node
        version: green
    spec:
      containers:
      - name: node
        image: kalianonymous/node-devops:v2
        ports:
        - containerPort: 3000
